### ISSUE TITLE
Should pass this i.s.o. callback to callback.apply

### ISSUE THREAD

**Issue by Download** [daffl/rubberduck#7]
I think there is an error in this code:

https://github.com/daffl/rubberduck/blob/master/lib/rubberduck.js#L50

Shouldn't `this` be passed as the first argument to `apply` ?

**Comment by daffl** [comment]
It should be `null` really because usually the callback context is not defined. Pre-bound methods (and arrow functions) should still have the correct context anyway.

**Comment by Download** [comment]
It should be `this`, as the wrapper function will receive the same `this` as the original function would have. If the original function would have received `null`, `this` in the wrapper will be `null`.

**Comment by Download** [comment]
Ah yes I missed that you already saved `this` as `context`. Thanks for the fix!

**Comment by daffl** [comment]
👍 Thanks for bringing it up. Definitely was a good fix.
